"""add class variable

Revision ID: 684d30129302
Revises: 01edbc11aeca
Create Date: 2023-01-27 14:47:37.425008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684d30129302'
down_revision = '01edbc11aeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('number_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_parution', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('date_parution')
        batch_op.drop_column('language')
        batch_op.drop_column('number_pages')
        batch_op.drop_column('book_url')

    # ### end Alembic commands ###
